# ==========================================
# QUERY CardCatalogDAO
# ==========================================
cardcatalog.addCatalog = INSERT INTO CardCatalog (sellerName) VALUES (?)
cardcatalog.remove = DELETE FROM Carta WHERE nome = ? AND venditore_username  = ?
cardcatalog.add = INSERT INTO Carta (nome, venditore_username, prezzo,livello, gradazione, attributo, tipo  ) " +
"VALUES (?, ?, ?, ?, ?, ?, ?)
cardcatalog.findCard = SELECT nome, prezzo, gradazione, venditore_username, livello, tipo, attributo FROM Carta WHERE nome LIKE ?








