user.findByUsername=SELECT * FROM Utenti WHERE username = ?
user.findByType=SELECT * FROM Utenti WHERE usertype = ?
catalog.getAllCards=SELECT * FROM catalogoVenditore WHERE idCarta NOT IN (SELECT o.idCarta FROM ordini o JOIN catalogoVenditore cv ON o.idCarta=cv.idCarta)
order.getUserOrder=SELECT * FROM ordini WHERE compratore = ?
order.getSellerOrder=SELECT * FROM ordini o JOIN catalogoVenditore cv ON o.idCarta=cv.idCarta WHERE cv.venditore = ?