# ==========================================
# QUERY CardCatalogDAO
# ==========================================
cardcatalog.addCatalog = INSERT INTO CardCatalog (sellerName) VALUES (?)
cardcatalog.remove = DELETE FROM Carta WHERE nome = ? AND venditore_username  = ?
cardcatalog.add = INSERT INTO Carta (nome, venditore_username, prezzo,livello, gradation, attributo, tipo  ) VALUES (?, ?, ?, ?, ?, ?, ?)
cardcatalog.findCard = SELECT nome, prezzo, gradation, venditore_username, livello, tipo, attributo FROM Carta WHERE nome LIKE ?
# ==========================================
# QUERY NotificationDAO
# ==========================================
notification.save = INSERT INTO Notifica (destinatario, mittente, messaggio, data, letta) VALUES (?, ?, ?, ?, FALSE)
notification.getUnread = SELECT id, destinatario, mittente, messaggio, data, letta FROM Notifica WHERE destinatario = ? AND letta = FALSE ORDER BY data DESC
notification.getAll = SELECT id, destinatario, mittente, messaggio, data, letta FROM Notifica WHERE destinatario = = ORDER BY data DESC
notification.markAsRead = UPDATE Notifica SET letta = TRUE WHERE id=?
# ==========================================
# QUERY FollowerDAO
# ==========================================
follower.follow = INSERT INTO Follower(venditore_username, username_compratore) VALUES (?,?)
follower.unfollow = DELETE FROM Follower WHERE venditore_username=? AND username_compratore=?
follower.getFollowers = SELECT username_compratore FROM Follower WHERE venditore_username = ?
follower.isFollowing = SELECT 1 FROM Follower WHERE username_compratore = ? AND venditore_username=?



